# Generated by Django 2.0.1 on 2018-10-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20181030_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
