# Generated by Django 2.0.1 on 2018-10-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='observaciones',
            field=models.TextField(max_length=150),
        ),
    ]
