# Generated by Django 2.0.1 on 2018-10-30 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='usuarios',
            field=models.ManyToManyField(through='reservas.Reserva', to=settings.AUTH_USER_MODEL),
        ),
    ]
