# Generated by Django 2.0.1 on 2018-10-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_recurso_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
